version: '3.8'

services:
  service1:
    build:
      context: ./service1
    ports:
      - "5000:5000"

  service2:
    build:
      context: ./service2
    ports:
      - "5001:5001"


  service3:
    build:
      context: ./service3
    ports:
      - "5002:5002"

